### ISSUE TITLE
Nested symbols not rendering

### ISSUE THREAD

**Issue by rodnem** [DWilliames/PDF-export-sketch-plugin#4]
Hi,
Thanks for your great job! 

I've got a little trouble when rendering nested symbols
Here is the comparison
![image](https://cloud.githubusercontent.com/assets/6350513/24239470/63ec02c0-0fae-11e7-8510-50cf0dbdbabb.png)

**Comment by DWilliames** [comment]
@rodnem Thanks mate. Are you able to provide the Sketch file you've used, so I can test against it?

**Comment by rodnem** [comment]
Great you're fast :)
Here it is.
[Nested-symbols-not-rendering-#4.sketch.zip](https://github.com/DWilliames/PDF-export-sketch-plugin/files/864134/Nested-symbols-not-rendering-.4.sketch.zip)

**Comment by DWilliames** [comment]
Thanks. I'll look into it now :)

**Comment by DWilliames** [comment]
@rodnem Sorry it took a while to get back to you. I spent quite a while trying to work around this... 
Unfortunately it's a limitation of Sketch 43. For example, if you select your symbol (with nested symbols), and go `'Layer > Detach from Symbol'`, it will not detach properly (retaining the states of the nested symbols).

Until that is fixed in Sketch, it is extremely difficult to try and overcome through my plugin. Sorry.

> I did reach out on the Sketch Plugins site — http://sketchplugins.com/d/121-detach-nested-symbols-by-replacing-with-group; to no avail
